substitutions:
  framework: esp-idf

packages:
  esp32: !include esp32.yaml

esp32_ble_tracker:
  scan_parameters:
    interval: 1100ms
    window: 1100ms
    active: true
  
bluetooth_proxy:
  active: true
