#Ethernet connection information
ethernet:
    type: LAN8720
    mdc_pin: GPIO23
    mdio_pin: GPIO18
    clk_mode: GPIO17_OUT
    phy_addr: 0

substitutions:
    project_name: "Zigstar.Lilyzig"
    project_version: "v2.0"
    rx_pin: GPIO36
    tx_pin: GPIO4
    zRST_gpio: GPIO16
    zbsl_gpio: GPIO32